### ISSUE TITLE
Inclusion in rofi or rofi-themes repository

### ISSUE THREAD

**Issue by carnager** [tinted-theming/base16-rofi#1]
Hi, would you mind if we incluide these themes in rofi or alternatively have them in the rofi-theme repositry?

**Comment by jordiorlando** [comment]
Of course, I'd be thrilled!

_Sent from my OnePlus ONEPLUS A3000 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by carnager** [comment]
cool. Though I found some issues for now. E.g. highlight background and normal/alternate background colors are the same, basically making the selected line impossible to see.

**Comment by jordiorlando** [comment]
I believe I did this intentionally, as everything else ended up looking strange. The highlighted line is visible because the foreground/text color is different. I can send a screencap if you'd like

_Sent from my OnePlus ONEPLUS A3000 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by carnager** [comment]
To be fair, you are right. Still, it's hardly visible

![rofi-2017-08-06-0222-00000](https://user-images.githubusercontent.com/3321178/28999640-3d3dec32-7a4e-11e7-896c-7dae7c91bfdc.png)

**Comment by jordiorlando** [comment]
Okay, any recommendations for what color I should use for that? I'll go ahead and change it if there's a better option.

_Sent from my OnePlus ONEPLUS A3000 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by ryanklee** [comment]
I agree with Carnager. From my perspective, at least a few of the themes are unuseable as is because it's nearly impossible to distinguish selected from unselected rows.

Base0B seems to work well for Onedark and Dracula. Here's a sceen shot of dracula with the modified theme: 
![2018-03-01-082716_1920x1200_scrot](https://user-images.githubusercontent.com/418460/36850388-41e5e6dc-1d2c-11e8-90cb-fed335ac3872.png)

**Comment by jordiorlando** [comment]
Closing as I no longer have time to dedicate to this project. Anyone who wishes to maintain, please let me know.
